name: CI

on:
  push:
    branches: [main]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-22.04
    steps:
      - name: Install protobuf
        shell: bash
        run: |
            sudo apt-get install protobuf-compiler
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
      - name: Cargo fmt
        run: cargo fmt --all -- --check
      - name: Cargo test
        run: cargo test --all-features
